
export const defaultPostScript = [
    '\'use strict\';',
    '',
    'export default class {',
    '',
    '   static configMeta = {',
    '      params: {',
    '         shift: {',
    '            type: \'number\',',
    '            description: \'Number of leds to shift by\',',
    '            default: 1,',
    '         }',
    '      }',
    '   }',
    '',
    '   #shift = 1;',
    '',
    '   setConfig(config) {',
    '      this.#shift = config.shift;',
    '   }',
    '',
    '   post(frame) {',
    '      if (this.#shift > 0) {',
    '         for (let i = 0; i < this.#shift; i++) {',
    '            const v = frame.shift();',
    '            frame.push(v);',
    '         }',
    '      } else {',
    '         for (let i = 0; i < this.#shift; i++) {',
    '            const v = frame.pop();',
    '            frame.unshift(v);',
    '         }',
    '      }',
    '   }',
    '',
    '}',

];